In [34]:
# import libraries
import numpy as np
import pandas as pd
import re

In [35]:
# read raw file
db = pd.read_csv('../data/raw/avg_rent_month.csv')

In [36]:
db.info()
db.head()

<class 'pandas.DataFrame'>
RangeIndex: 326 entries, 0 to 325
Data columns (total 31 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Month                              326 non-null    str
 1   Class A Hong Kong                  326 non-null    int64
 2   Class A Hong Kong - Remarks        3 non-null      str
 3   Class A Kowloon                    326 non-null    int64
 4   Class A Kowloon - Remarks          3 non-null      str
 5   Class A New Territories            326 non-null    int64
 6   Class A New Territories - Remarks  3 non-null      str
 7   Class B Hong Kong                  326 non-null    int64
 8   Class B Hong Kong - Remarks        3 non-null      str
 9   Class B Kowloon                    326 non-null    int64
 10  Class B Kowloon - Remarks          3 non-null      str
 11  Class B New Territories            326 non-null    int64
 12  Class B New Territories - Remarks  3 non-null      str
 13  Class C Hong Kong                  326 non-null    int64
 14  Class C Hong Kong - Remarks        9 non-null      str
 15  Class C Kowloon                    326 non-null    int64
 16  Class C Kowloon - Remarks          13 non-null     str
 17  Class C New Territories            326 non-null    int64
 18  Class C New Territories - Remarks  9 non-null      str
 19  Class D Hong Kong                  326 non-null    int64
 20  Class D Hong Kong - Remarks        13 non-null     str
 21  Class D Kowloon                    326 non-null    int64
 22  Class D Kowloon - Remarks          40 non-null     str
 23  Class D New Territories            326 non-null    int64
 24  Class D New Territories - Remarks  17 non-null     str
 25  Class E Hong Kong                  326 non-null    int64
 26  Class E Hong Kong - Remarks        12 non-null     str
 27  Class E Kowloon                    326 non-null    str
 28  Class E Kowloon - Remarks          320 non-null    str
 29  Class E New Territories            326 non-null    str
 30  Class E New Territories - Remarks  146 non-null    str
dtypes: int64(13), str(18)
memory usage: 79.1 KB

,Month,Class A Hong Kong,Class A Hong Kong - Remarks,Class A Kowloon,Class A Kowloon - Remarks,Class A New Territories,Class A New Territories - Remarks,Class B Hong Kong,Class B Hong Kong - Remarks,Class B Kowloon,...,Class D Kowloon,Class D Kowloon - Remarks,Class D New Territories,Class D New Territories - Remarks,Class E Hong Kong,Class E Hong Kong - Remarks,Class E Kowloon,Class E Kowloon - Remarks,Class E New Territories,Class E New Territories - Remarks
0,Jan-99,190,NaN,171,NaN,133,NaN,199,NaN,165,...,198,NaN,185,NaN,301,NaN,185,NaN,191,NaN
1,Feb-99,196,NaN,173,NaN,133,NaN,204,NaN,165,...,196,Z,173,NaN,311,NaN,213,Z,152,NaN
2,Mar-99,199,NaN,170,NaN,133,NaN,197,NaN,160,...,174,NaN,186,NaN,301,NaN,194,Z,190,Z
3,Apr-99,191,NaN,171,NaN,135,NaN,200,NaN,156,...,172,NaN,170,NaN,313,NaN,221,Z,172,NaN
4,May-99,191,NaN,175,NaN,127,NaN,188,NaN,155,...,180,NaN,180,NaN,289,NaN,168,Z,162,Z

Remarks:
1. Delete all the Remarks columns.

In [37]:
# find all columns with "Remarks" in the name
remark_cols = [col for col in db.columns if re.search(r'Remarks', col, re.IGNORECASE)]

# replace "Remarks" with "< 20 transactions" in those column names
db.rename(columns={col: col.replace('Remarks', '< 20 transactions') for col in remark_cols}, inplace=True)

In [38]:
db.head()

,Month,Class A Hong Kong,Class A Hong Kong - < 20 transactions,Class A Kowloon,Class A Kowloon - < 20 transactions,Class A New Territories,Class A New Territories - < 20 transactions,Class B Hong Kong,Class B Hong Kong - < 20 transactions,Class B Kowloon,...,Class D Kowloon,Class D Kowloon - < 20 transactions,Class D New Territories,Class D New Territories - < 20 transactions,Class E Hong Kong,Class E Hong Kong - < 20 transactions,Class E Kowloon,Class E Kowloon - < 20 transactions,Class E New Territories,Class E New Territories - < 20 transactions
0,Jan-99,190,NaN,171,NaN,133,NaN,199,NaN,165,...,198,NaN,185,NaN,301,NaN,185,NaN,191,NaN
1,Feb-99,196,NaN,173,NaN,133,NaN,204,NaN,165,...,196,Z,173,NaN,311,NaN,213,Z,152,NaN
2,Mar-99,199,NaN,170,NaN,133,NaN,197,NaN,160,...,174,NaN,186,NaN,301,NaN,194,Z,190,Z
3,Apr-99,191,NaN,171,NaN,135,NaN,200,NaN,156,...,172,NaN,170,NaN,313,NaN,221,Z,172,NaN
4,May-99,191,NaN,175,NaN,127,NaN,188,NaN,155,...,180,NaN,180,NaN,289,NaN,168,Z,162,Z

In [39]:
# Change Null values to False, and Z to True
db.replace({np.nan: False, 'Z': True}, inplace=True)

,Month,Class A Hong Kong,Class A Hong Kong - < 20 transactions,Class A Kowloon,Class A Kowloon - < 20 transactions,Class A New Territories,Class A New Territories - < 20 transactions,Class B Hong Kong,Class B Hong Kong - < 20 transactions,Class B Kowloon,...,Class D Kowloon,Class D Kowloon - < 20 transactions,Class D New Territories,Class D New Territories - < 20 transactions,Class E Hong Kong,Class E Hong Kong - < 20 transactions,Class E Kowloon,Class E Kowloon - < 20 transactions,Class E New Territories,Class E New Territories - < 20 transactions
0,Jan-99,190,False,171,False,133,False,199,False,165,...,198,False,185,False,301,False,185,False,191,False
1,Feb-99,196,False,173,False,133,False,204,False,165,...,196,True,173,False,311,False,213,True,152,False
2,Mar-99,199,False,170,False,133,False,197,False,160,...,174,False,186,False,301,False,194,True,190,True
3,Apr-99,191,False,171,False,135,False,200,False,156,...,172,False,170,False,313,False,221,True,172,False
4,May-99,191,False,175,False,127,False,188,False,155,...,180,False,180,False,289,False,168,True,162,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,Oct-25,490,False,449,False,337,False,432,False,377,...,359,False,241,False,480,False,492,True,225,False
322,Nov-25,500,False,448,False,333,False,439,False,390,...,392,False,239,False,494,False,423,True,201,False
323,Dec-25,512,P,441,P,343,P,418,P,376,...,447,P,236,P,466,P,-,P,179,PZ
324,Jan-26,518,P,446,P,347,P,427,P,381,...,411,P,251,P,469,P,305,PZ,234,PZ
325,Feb-26,539,P,456,P,349,P,424,P,393,...,411,PZ,248,P,490,P,479,PZ,230,PZ

In [40]:
# Convert columns with "< 20 transactions" to boolean data type
transaction_cols = [col for col in db.columns if '< 20 transactions' in col]
db[transaction_cols] = db[transaction_cols].astype(bool)

Remarks:
1. The information of Dec-25, Jan-26, Feb-26 are provisional, aren't going to use it.
2. Only analysis Nov-15 to Nov-25 data.

In [41]:
# Change Month column to datetime format
db['Month'] = pd.to_datetime(db['Month'], format='%b-%y')

# Delete row excluding the period Nov-24 to Oct-25
db = db[(db['Month'] >= pd.to_datetime('Nov-15', format='%b-%y')) & (db['Month'] <= pd.to_datetime('Nov-25', format='%b-%y'))]

In [42]:
db.head(12)

,Month,Class A Hong Kong,Class A Hong Kong - < 20 transactions,Class A Kowloon,Class A Kowloon - < 20 transactions,Class A New Territories,Class A New Territories - < 20 transactions,Class B Hong Kong,Class B Hong Kong - < 20 transactions,Class B Kowloon,...,Class D Kowloon,Class D Kowloon - < 20 transactions,Class D New Territories,Class D New Territories - < 20 transactions,Class E Hong Kong,Class E Hong Kong - < 20 transactions,Class E Kowloon,Class E Kowloon - < 20 transactions,Class E New Territories,Class E New Territories - < 20 transactions
202,2015-11-01,430,False,327,False,265,False,391,False,316,...,333,False,249,False,465,False,299,True,246,True
203,2015-12-01,433,False,323,False,263,False,379,False,303,...,316,False,254,False,454,False,296,True,248,True
204,2016-01-01,432,False,314,False,255,False,365,False,299,...,341,False,261,False,427,False,341,True,231,True
205,2016-02-01,407,False,308,False,249,False,361,False,288,...,337,False,281,False,435,False,346,True,246,True
206,2016-03-01,396,False,303,False,249,False,353,False,299,...,305,False,261,False,442,False,322,True,229,False
207,2016-04-01,385,False,310,False,241,False,355,False,286,...,298,False,258,False,417,False,406,True,208,True
208,2016-05-01,398,False,310,False,251,False,364,False,289,...,305,False,236,False,427,False,310,True,227,False
209,2016-06-01,419,False,319,False,262,False,375,False,295,...,343,False,229,False,436,False,413,True,214,False
210,2016-07-01,427,False,355,False,277,False,383,False,307,...,336,False,235,False,431,False,371,True,223,False
211,2016-08-01,429,False,344,False,282,False,377,False,309,...,340,False,250,False,441,False,297,True,260,False
212,2016-09-01,422,False,334,False,272,False,377,False,310,...,339,False,239,False,427,False,430,True,243,False
213,2016-10-01,422,False,338,False,278,False,379,False,314,...,321,False,242,False,431,False,317,True,254,True

In [43]:
db.tail(12)

,Month,Class A Hong Kong,Class A Hong Kong - < 20 transactions,Class A Kowloon,Class A Kowloon - < 20 transactions,Class A New Territories,Class A New Territories - < 20 transactions,Class B Hong Kong,Class B Hong Kong - < 20 transactions,Class B Kowloon,...,Class D Kowloon,Class D Kowloon - < 20 transactions,Class D New Territories,Class D New Territories - < 20 transactions,Class E Hong Kong,Class E Hong Kong - < 20 transactions,Class E Kowloon,Class E Kowloon - < 20 transactions,Class E New Territories,Class E New Territories - < 20 transactions
311,2024-12-01,475,False,424,False,331,False,401,False,368,...,369,False,259,False,442,False,350,True,202,False
312,2025-01-01,488,False,419,False,339,False,397,False,360,...,343,False,242,False,432,False,448,True,222,False
313,2025-02-01,477,False,433,False,336,False,406,False,359,...,371,False,256,False,490,False,340,True,239,False
314,2025-03-01,476,False,427,False,341,False,397,False,365,...,364,False,257,False,465,False,382,True,190,False
315,2025-04-01,469,False,415,False,337,False,406,False,363,...,353,False,243,False,451,False,424,True,207,False
316,2025-05-01,494,False,433,False,341,False,403,False,372,...,367,False,225,False,466,False,287,True,230,False
317,2025-06-01,499,False,429,False,337,False,417,False,366,...,379,False,259,False,454,False,335,True,217,False
318,2025-07-01,503,False,432,False,346,False,408,False,366,...,392,False,249,False,430,False,309,True,229,False
319,2025-08-01,516,False,467,False,368,False,411,False,384,...,374,False,254,False,445,False,423,True,242,False
320,2025-09-01,502,False,467,False,338,False,415,False,380,...,384,False,232,False,450,False,540,True,219,False
321,2025-10-01,490,False,449,False,337,False,432,False,377,...,359,False,241,False,480,False,492,True,225,False
322,2025-11-01,500,False,448,False,333,False,439,False,390,...,392,False,239,False,494,False,423,True,201,False

In [44]:
db.info()

<class 'pandas.DataFrame'>
RangeIndex: 121 entries, 202 to 322
Data columns (total 31 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Month                                        121 non-null    datetime64[us]
 1   Class A Hong Kong                            121 non-null    int64
 2   Class A Hong Kong - < 20 transactions        121 non-null    bool
 3   Class A Kowloon                              121 non-null    int64
 4   Class A Kowloon - < 20 transactions          121 non-null    bool
 5   Class A New Territories                      121 non-null    int64
 6   Class A New Territories - < 20 transactions  121 non-null    bool
 7   Class B Hong Kong                            121 non-null    int64
 8   Class B Hong Kong - < 20 transactions        121 non-null    bool
 9   Class B Kowloon                              121 non-null    int64
 10  Class B Kowloon - < 20 transactions          121 non-null    bool
 11  Class B New Territories                      121 non-null    int64
 12  Class B New Territories - < 20 transactions  121 non-null    bool
 13  Class C Hong Kong                            121 non-null    int64
 14  Class C Hong Kong - < 20 transactions        121 non-null    bool
 15  Class C Kowloon                              121 non-null    int64
 16  Class C Kowloon - < 20 transactions          121 non-null    bool
 17  Class C New Territories                      121 non-null    int64
 18  Class C New Territories - < 20 transactions  121 non-null    bool
 19  Class D Hong Kong                            121 non-null    int64
 20  Class D Hong Kong - < 20 transactions        121 non-null    bool
 21  Class D Kowloon                              121 non-null    int64
 22  Class D Kowloon - < 20 transactions          121 non-null    bool
 23  Class D New Territories                      121 non-null    int64
 24  Class D New Territories - < 20 transactions  121 non-null    bool
 25  Class E Hong Kong                            121 non-null    int64
 26  Class E Hong Kong - < 20 transactions        121 non-null    bool
 27  Class E Kowloon                              121 non-null    str
 28  Class E Kowloon - < 20 transactions          121 non-null    bool
 29  Class E New Territories                      121 non-null    str
 30  Class E New Territories - < 20 transactions  121 non-null    bool
dtypes: bool(15), datetime64[us](1), int64(13), str(2)
memory usage: 17.0 KB

In [45]:
db.select_dtypes(include=['object']).dtypes

/var/folders/rd/j8_t5hfx3jq8xs2jsmb5z95m0000gn/T/ipykernel_53712/1208895062.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  db.select_dtypes(include=['object']).dtypes

Class E Kowloon            str
Class E New Territories    str
dtype: object

In [46]:
# Convert string columns to int64
string_cols = db.select_dtypes(include=['object']).columns
for col in string_cols:
    db[col] = pd.to_numeric(db[col], errors='coerce').fillna(0).astype('int64')

/var/folders/rd/j8_t5hfx3jq8xs2jsmb5z95m0000gn/T/ipykernel_53712/23956205.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  string_cols = db.select_dtypes(include=['object']).columns

In [48]:
db.info()

<class 'pandas.DataFrame'>
RangeIndex: 121 entries, 202 to 322
Data columns (total 31 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   Month                                        121 non-null    datetime64[us]
 1   Class A Hong Kong                            121 non-null    int64
 2   Class A Hong Kong - < 20 transactions        121 non-null    bool
 3   Class A Kowloon                              121 non-null    int64
 4   Class A Kowloon - < 20 transactions          121 non-null    bool
 5   Class A New Territories                      121 non-null    int64
 6   Class A New Territories - < 20 transactions  121 non-null    bool
 7   Class B Hong Kong                            121 non-null    int64
 8   Class B Hong Kong - < 20 transactions        121 non-null    bool
 9   Class B Kowloon                              121 non-null    int64
 10  Class B Kowloon - < 20 transactions          121 non-null    bool
 11  Class B New Territories                      121 non-null    int64
 12  Class B New Territories - < 20 transactions  121 non-null    bool
 13  Class C Hong Kong                            121 non-null    int64
 14  Class C Hong Kong - < 20 transactions        121 non-null    bool
 15  Class C Kowloon                              121 non-null    int64
 16  Class C Kowloon - < 20 transactions          121 non-null    bool
 17  Class C New Territories                      121 non-null    int64
 18  Class C New Territories - < 20 transactions  121 non-null    bool
 19  Class D Hong Kong                            121 non-null    int64
 20  Class D Hong Kong - < 20 transactions        121 non-null    bool
 21  Class D Kowloon                              121 non-null    int64
 22  Class D Kowloon - < 20 transactions          121 non-null    bool
 23  Class D New Territories                      121 non-null    int64
 24  Class D New Territories - < 20 transactions  121 non-null    bool
 25  Class E Hong Kong                            121 non-null    int64
 26  Class E Hong Kong - < 20 transactions        121 non-null    bool
 27  Class E Kowloon                              121 non-null    int64
 28  Class E Kowloon - < 20 transactions          121 non-null    bool
 29  Class E New Territories                      121 non-null    int64
 30  Class E New Territories - < 20 transactions  121 non-null    bool
dtypes: bool(15), datetime64[us](1), int64(15)
memory usage: 17.0 KB

In [47]:
# save changes to cleaned file
db.to_csv('../data/cleaned/avg_rent_month_cleaned.csv', index=False)